services:
  backend:
    build:
      context: ./backend_notes
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://host.docker.internal:27017/notes-app
      - PORT=5000
      - URL_Front=http://frontend:3000
    networks:
      - backend-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend-notes
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
